// One-shot CSV → data.ts converter. Run via `npm run build:data`.
// Re-run any time the source CSVs in /data change.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const dataDir = join(root, "data");
const out = join(root, "src", "data.ts");

function parseCSV(text) {
  // Newspaper CSVs only — no embedded quotes/commas in fields. Simple split is safe.
  const lines = text.trim().split(/\r?\n/);
  const headers = lines[0].split(",");
  return lines.slice(1).map((line) => {
    const cells = line.split(",");
    const row = {};
    headers.forEach((h, i) => {
      row[h] = cells[i];
    });
    return row;
  });
}

function num(v) {
  if (v === undefined || v === "" || v === "nan") return 0;
  const n = Number(v);
  return Number.isFinite(n) ? n : 0;
}

const playersRaw = parseCSV(readFileSync(join(dataDir, "player_totals.csv"), "utf8"));
const players = playersRaw.map((r) => ({
  Player: r.Player,
  TotalNet: num(r.TotalNet),
  Games: num(r.Games),
  Avg: num(r.Avg),
  WinPct: num(r.WinPct),
  PLONet: num(r.PLONet),
  PLOGames: num(r.PLOGames),
  PLOAvg: num(r.PLOAvg),
  PLOWinPct: num(r.PLOWinPct),
  NLNet: num(r.NLNet),
  NLGames: num(r.NLGames),
  NLAvg: num(r.NLAvg),
  NLWinPct: num(r.NLWinPct),
}));

const gamesRaw = parseCSV(readFileSync(join(dataDir, "games.csv"), "utf8"));
const games = gamesRaw.map((r) => ({
  date: r.date,
  game_num: Number(r.game_num),
  game_type: r.game_type,
  player: r.player,
  net: num(r.net),
}));

// Cumulative is wide. Convert to: { date, [player]: number }[]
const cumText = readFileSync(join(dataDir, "cumulative_by_date.csv"), "utf8");
const cumLines = cumText.trim().split(/\r?\n/);
const cumHeaders = cumLines[0].split(",");
const cumulative = cumLines.slice(1).map((line) => {
  const cells = line.split(",");
  const row = { date: cells[0] };
  for (let i = 1; i < cumHeaders.length; i++) {
    row[cumHeaders[i]] = num(cells[i]);
  }
  return row;
});

const banner = "// AUTO-GENERATED by scripts/build-data.mjs — do not edit by hand.\n// Source: data/*.csv. Re-run `npm run build:data` after editing the CSVs.\n";

const ts = `${banner}
export interface Player {
  Player: string;
  TotalNet: number;
  Games: number;
  Avg: number;
  WinPct: number;
  PLONet: number;
  PLOGames: number;
  PLOAvg: number;
  PLOWinPct: number;
  NLNet: number;
  NLGames: number;
  NLAvg: number;
  NLWinPct: number;
}

export interface Game {
  date: string;
  game_num: number;
  game_type: "PLO" | "NL";
  player: string;
  net: number;
}

export type CumulativeRow = { date: string } & Record<string, number | string>;

export const players: Player[] = ${JSON.stringify(players, null, 2)};

export const games: Game[] = ${JSON.stringify(games)};

export const cumulative: CumulativeRow[] = ${JSON.stringify(cumulative, null, 2)};
`;

writeFileSync(out, ts);
console.log(`Wrote ${out} — ${players.length} players, ${games.length} games, ${cumulative.length} dates`);
